### ISSUE TITLE
REL: bigdiff-code 0.1.0 release schedule

### ISSUE THREAD

**Issue by sangheestyle** [sangheestyle/bigdiff-code#8]
We need to release bigdiff-code 0.1.0.
### Release Schedule

The releases:
- 0.1.0: Feburary 22, 2015
- 0.1.1: Feburary 24, 2015
### Features for 0.1.0
- [x] sangheestyle/bigdiff-code#1
- [x] sangheestyle/bigdiff-code#2
- [x] sangheestyle/bigdiff-code#3
### Misc

This version is for our presentation.
